# Generated by Django 2.0.13 on 2020-09-18 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MysteryGame', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bandcharacter',
            name='code',
            field=models.CharField(default='oops', max_length=10),
            preserve_default=False,
        ),
    ]
